# Name of the project and initial config info
name: 'da_marketing'
version: '1.0.0'
dbt-cloud:
    project-id: 70437463662272
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'analytics'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"