name: Trigger demo slim CI job

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch: {}

jobs:
  trigger-slim-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Trigger slim CI job in dbt Cloud
        env:
          DBT_SERVICE_TOKEN: ${{ secrets.DBT_SERVICE_TOKEN }}
          DBT_ACCOUNT_ID: ${{ vars.DBT_ACCOUNT_ID }}
          DBT_JOB_ID: ${{ vars.DBT_JOB_ID }}
          PR_ID: ${{ vars.PR_ID }}
          GIT_SHA: ${{ vars.GIT_SHA }}
          DBT_BASE_URL: ${{ vars.DBT_BASE_URL }}
        run: python scripts/trigger_slim_ci_job.py
